# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by t.he analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Performance
    avoid_print: true
    avoid_slow_async_io: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true

    # Code quality
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true

    # Error prevention
    always_declare_return_types: true
    avoid_empty_else: true
    close_sinks: true
    cancel_subscriptions: true
    hash_and_equals: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    use_build_context_synchronously: true

    # Style & readability
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    file_names: true
    library_names: true
    non_constant_identifier_names: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    recursive_getters: true
    sort_child_properties_last: true
    unnecessary_this: true
    use_string_buffers: true